"""Standalone Agent HTTP/SSE transport binding.

Importing this package requires the optional ``http`` extra.  The core CLI
and in-process adapter intentionally do not import it.
"""

from coding_agent_neo.transports.http.app import (
    build_app,
    build_http_app,
    create_app,
    create_http_app,
)
from coding_agent_neo.transports.http.commands import (
    CommandDecodeError,
    CommandDecoder,
    decode_command,
)
from coding_agent_neo.transports.http.registry import (
    AgentBackendProvider,
    RegistrySnapshot,
    SessionExistsError,
    SessionRegistry,
    TransportSession,
    TransportSessionRegistry,
)
from coding_agent_neo.transports.http.wire import (
    BASE_PATH,
    HEALTH_PATH,
    HISTORY_EVENT_DEFAULT_LIMIT,
    HISTORY_EVENT_MAX_LIMIT,
    HISTORY_EVENT_PAYLOAD_MAX_BYTES,
    HISTORY_LIST_DEFAULT_LIMIT,
    HISTORY_LIST_MAX_LIMIT,
    HISTORY_PAGE_MAX_BYTES,
    HISTORY_SEQUENCE_MAX,
    PROTOCOL_VERSION,
    SESSIONS_PATH,
    SSE_MEDIA_TYPE,
    AcceptedResponse,
    CursorError,
    HealthResponse,
    HistoryCursorError,
    HistoryIdError,
    HistoryLimitError,
    SessionCreatedResponse,
    SessionStatusResponse,
    encode_keepalive,
    encode_sse,
    error_body,
    event_json,
    event_page_to_dict,
    event_to_dict,
    history_page_to_dict,
    parse_cursor,
    parse_history_id,
    parse_history_limit,
    parse_history_list_cursor,
    parse_history_sequence,
    select_cursor,
)

__all__ = [
    "AcceptedResponse",
    "AgentBackendProvider",
    "BASE_PATH",
    "CommandDecodeError",
    "CommandDecoder",
    "CursorError",
    "HISTORY_EVENT_DEFAULT_LIMIT",
    "HISTORY_EVENT_MAX_LIMIT",
    "HISTORY_EVENT_PAYLOAD_MAX_BYTES",
    "HISTORY_LIST_DEFAULT_LIMIT",
    "HISTORY_LIST_MAX_LIMIT",
    "HISTORY_PAGE_MAX_BYTES",
    "HISTORY_SEQUENCE_MAX",
    "HEALTH_PATH",
    "HealthResponse",
    "HistoryCursorError",
    "HistoryIdError",
    "HistoryLimitError",
    "PROTOCOL_VERSION",
    "RegistrySnapshot",
    "SSE_MEDIA_TYPE",
    "SESSIONS_PATH",
    "SessionCreatedResponse",
    "SessionExistsError",
    "SessionRegistry",
    "SessionStatusResponse",
    "TransportSession",
    "TransportSessionRegistry",
    "build_app",
    "build_http_app",
    "create_app",
    "create_http_app",
    "decode_command",
    "encode_keepalive",
    "encode_sse",
    "error_body",
    "event_page_to_dict",
    "event_json",
    "event_to_dict",
    "history_page_to_dict",
    "parse_history_id",
    "parse_history_limit",
    "parse_history_list_cursor",
    "parse_history_sequence",
    "parse_cursor",
    "select_cursor",
]
