"""Execution-environment contracts and the local backend."""

from coding_agent_neo.environment.base import (
    CommandRequest,
    CommandResult,
    EditFileRequest,
    EditFileResult,
    EnvironmentRequest,
    EnvironmentResponse,
    ExecutionEnvironment,
    FileResult,
    ListFilesRequest,
    ListResult,
    ReadFileRequest,
    ReadFileResult,
    RunCommandRequest,
    RunCommandResult,
    SearchRequest,
    SearchResult,
    WriteFileRequest,
    WriteFileResult,
)
from coding_agent_neo.environment.local import LocalEnvironment, LocalExecutionEnvironment

__all__ = [
    "CommandRequest",
    "CommandResult",
    "EditFileRequest",
    "EditFileResult",
    "EnvironmentRequest",
    "EnvironmentResponse",
    "ExecutionEnvironment",
    "FileResult",
    "ListFilesRequest",
    "ListResult",
    "ReadFileRequest",
    "ReadFileResult",
    "RunCommandRequest",
    "RunCommandResult",
    "SearchRequest",
    "SearchResult",
    "WriteFileRequest",
    "WriteFileResult",
    "LocalEnvironment",
    "LocalExecutionEnvironment",
]
